/**
 * Strategic Archetype Definitions
 * 
 * En Pensent™ Color Flow Archetypes
 */

import { StrategicArchetype, ArchetypeDefinition } from './types';

export const ARCHETYPE_DEFINITIONS: Record<StrategicArchetype, ArchetypeDefinition> = {
  kingside_attack: {
    id: 'kingside_attack',
    name: 'Kingside Attack',
    description: 'Concentrated piece activity toward the enemy king',
    colorCharacteristics: 'Heavy warm colors (h-file), intensifying near enemy king',
    historicalWinRate: 0.58,
    predictedOutcome: 'white_favored',
    lookaheadConfidence: 15,
  },
  queenside_expansion: {
    id: 'queenside_expansion',
    name: 'Queenside Expansion',
    description: 'Systematic territorial gain on the a-d files',
    colorCharacteristics: 'Gradual color spread from center to a-file',
    historicalWinRate: 0.54,
    predictedOutcome: 'white_favored',
    lookaheadConfidence: 20,
  },
  central_domination: {
    id: 'central_domination',
    name: 'Central Domination',
    description: 'Dense control of d4-e5 complex',
    colorCharacteristics: 'Intense overlapping colors in center squares',
    historicalWinRate: 0.62,
    predictedOutcome: 'white_favored',
    lookaheadConfidence: 25,
  },
  prophylactic_defense: {
    id: 'prophylactic_defense',
    name: 'Prophylactic Defense',
    description: 'Counter-reactive, preventing opponent threats',
    colorCharacteristics: 'Low intensity, balanced distribution, reactive patterns',
    historicalWinRate: 0.48,
    predictedOutcome: 'balanced',
    lookaheadConfidence: 30,
  },
  pawn_storm: {
    id: 'pawn_storm',
    name: 'Pawn Storm',
    description: 'Advancing pawn chain creating color trail',
    colorCharacteristics: 'Linear pawn color progression, single-color trails',
    historicalWinRate: 0.55,
    predictedOutcome: 'white_favored',
    lookaheadConfidence: 12,
  },
  piece_harmony: {
    id: 'piece_harmony',
    name: 'Piece Harmony',
    description: 'Coordinated piece placement with color overlap',
    colorCharacteristics: 'Multiple piece colors layered on same squares',
    historicalWinRate: 0.60,
    predictedOutcome: 'white_favored',
    lookaheadConfidence: 18,
  },
  opposite_castling: {
    id: 'opposite_castling',
    name: 'Opposite Side Castling',
    description: 'Race to attack opposite flanks',
    colorCharacteristics: 'Split warm/cold territories, high edge intensity',
    historicalWinRate: 0.51,
    predictedOutcome: 'balanced',
    lookaheadConfidence: 10,
  },
  closed_maneuvering: {
    id: 'closed_maneuvering',
    name: 'Closed Maneuvering',
    description: 'Slow positional regrouping',
    colorCharacteristics: 'Low volatility, gradual color shifts, knight activity',
    historicalWinRate: 0.52,
    predictedOutcome: 'balanced',
    lookaheadConfidence: 35,
  },
  open_tactical: {
    id: 'open_tactical',
    name: 'Open Tactical Battle',
    description: 'High-piece activity, captures, exchanges',
    colorCharacteristics: 'High volatility, sparse but intense color bursts',
    historicalWinRate: 0.53,
    predictedOutcome: 'balanced',
    lookaheadConfidence: 8,
  },
  endgame_technique: {
    id: 'endgame_technique',
    name: 'Endgame Technique',
    description: 'Precise maneuvering with few pieces',
    colorCharacteristics: 'Minimal colors, king/pawn dominant, precise paths',
    historicalWinRate: 0.58,
    predictedOutcome: 'white_favored',
    lookaheadConfidence: 40,
  },
  sacrificial_attack: {
    id: 'sacrificial_attack',
    name: 'Sacrificial Attack',
    description: 'Material sacrifice for initiative',
    colorCharacteristics: 'Asymmetric intensity, heavy attacker presence despite fewer pieces',
    historicalWinRate: 0.56,
    predictedOutcome: 'white_favored',
    lookaheadConfidence: 6,
  },
  positional_squeeze: {
    id: 'positional_squeeze',
    name: 'Positional Squeeze',
    description: 'Gradual space restriction',
    colorCharacteristics: 'Slow territorial expansion, compressing opponent colors',
    historicalWinRate: 0.61,
    predictedOutcome: 'white_favored',
    lookaheadConfidence: 28,
  },
  unknown: {
    id: 'unknown',
    name: 'Unclassified Pattern',
    description: 'Novel or hybrid strategic approach',
    colorCharacteristics: 'Does not match known archetypes',
    historicalWinRate: 0.50,
    predictedOutcome: 'balanced',
    lookaheadConfidence: 5,
  },
};
